package Cube;

public class BlockModel {
	
	public static int Building[] = {
			
		// x, y, z, TYPE
		11, 1, 11, Block.TYPE.BLACK_CLAY.ordinal(),
		12, 1, 11, Block.TYPE.BLACK_CLAY.ordinal(),
		13, 1, 11, Block.TYPE.BLACK_CLAY.ordinal(),
		14, 1, 11, Block.TYPE.BLACK_CLAY.ordinal(),
		15, 1, 11, Block.TYPE.BLACK_CLAY.ordinal(),
		16, 1, 11, Block.TYPE.BLACK_CLAY.ordinal(),
		17, 1, 11, Block.TYPE.BLACK_CLAY.ordinal(),
		18, 1, 11, Block.TYPE.BLACK_CLAY.ordinal(),
		19, 1, 11, Block.TYPE.BLACK_CLAY.ordinal(),
		20, 1, 11, Block.TYPE.BLACK_CLAY.ordinal(),
		
		11, 1, 20, Block.TYPE.BLACK_CLAY.ordinal(),
		12, 1, 20, Block.TYPE.BLACK_CLAY.ordinal(),
		13, 1, 20, Block.TYPE.BLACK_CLAY.ordinal(),
		14, 1, 20, Block.TYPE.BLACK_CLAY.ordinal(),
//		15, 1, 20, Block.TYPE.BLACK_CLAY.ordinal(),
//		16, 1, 20, Block.TYPE.BLACK_CLAY.ordinal(),
		17, 1, 20, Block.TYPE.BLACK_CLAY.ordinal(),
		18, 1, 20, Block.TYPE.BLACK_CLAY.ordinal(),
		19, 1, 20, Block.TYPE.BLACK_CLAY.ordinal(),
		20, 1, 20, Block.TYPE.BLACK_CLAY.ordinal(),

		11, 1, 12, Block.TYPE.BLACK_CLAY.ordinal(),
		11, 1, 13, Block.TYPE.BLACK_CLAY.ordinal(),
		11, 1, 14, Block.TYPE.BLACK_CLAY.ordinal(),
		11, 1, 15, Block.TYPE.BLACK_CLAY.ordinal(),
		11, 1, 16, Block.TYPE.BLACK_CLAY.ordinal(),
		11, 1, 17, Block.TYPE.BLACK_CLAY.ordinal(),
		11, 1, 18, Block.TYPE.BLACK_CLAY.ordinal(),
		11, 1, 19, Block.TYPE.BLACK_CLAY.ordinal(),

		20, 1, 12, Block.TYPE.BLACK_CLAY.ordinal(),
		20, 1, 13, Block.TYPE.BLACK_CLAY.ordinal(),
		20, 1, 14, Block.TYPE.BLACK_CLAY.ordinal(),
		20, 1, 15, Block.TYPE.BLACK_CLAY.ordinal(),
		20, 1, 16, Block.TYPE.BLACK_CLAY.ordinal(),
		20, 1, 17, Block.TYPE.BLACK_CLAY.ordinal(),
		20, 1, 18, Block.TYPE.BLACK_CLAY.ordinal(),
		20, 1, 19, Block.TYPE.BLACK_CLAY.ordinal(),
		
		// y = 2
		
	};
	
	public static int Building2[] = {
			
			// x, y, z, TYPE
			
			// garage side
			24, 1, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 1, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			25, 1, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 1, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			24, 2, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 2, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			25, 2, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 2, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			24, 3, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 3, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			25, 3, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 3, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			24, 4, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 4, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			25, 4, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 4, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			24, 5, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 5, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			25, 5, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 5, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			24, 6, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 6, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			25, 6, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 6, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			24, 7, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			24, 7, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			25, 7, 29, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 28, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 27, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 26, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 25, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 24, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 23, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 22, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 21, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 20, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 19, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 18, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 17, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 16, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			25, 7, 15, Block.TYPE.STONE_BRICK_CRACKED.ordinal(),
			
			// white top
			25, 5, 30, Block.TYPE.WHITE_CLAY.ordinal(),
			26, 5, 30, Block.TYPE.WHITE_CLAY.ordinal(),
			27, 5, 30, Block.TYPE.WHITE_CLAY.ordinal(),
			28, 5, 30, Block.TYPE.WHITE_CLAY.ordinal(),
			29, 5, 30, Block.TYPE.WHITE_CLAY.ordinal(),
			30, 5, 30, Block.TYPE.WHITE_CLAY.ordinal(),
			
			26, 5, 29, Block.TYPE.WHITE_CLAY.ordinal(),
			27, 5, 29, Block.TYPE.WHITE_CLAY.ordinal(),
			28, 5, 29, Block.TYPE.WHITE_CLAY.ordinal(),
			29, 5, 29, Block.TYPE.WHITE_CLAY.ordinal(),
			30, 5, 29, Block.TYPE.WHITE_CLAY.ordinal(),
			
			26, 5, 28, Block.TYPE.WHITE_CLAY.ordinal(),
			27, 5, 28, Block.TYPE.WHITE_CLAY.ordinal(),
			28, 5, 28, Block.TYPE.WHITE_CLAY.ordinal(),
			29, 5, 28, Block.TYPE.WHITE_CLAY.ordinal(),
			30, 5, 28, Block.TYPE.WHITE_CLAY.ordinal(),
			
			26, 5, 27, Block.TYPE.WHITE_CLAY.ordinal(),
			27, 5, 27, Block.TYPE.WHITE_CLAY.ordinal(),
			28, 5, 27, Block.TYPE.WHITE_CLAY.ordinal(),
			29, 5, 27, Block.TYPE.WHITE_CLAY.ordinal(),
			30, 5, 27, Block.TYPE.WHITE_CLAY.ordinal(),
			
			26, 5, 26, Block.TYPE.WHITE_CLAY.ordinal(),
			27, 5, 26, Block.TYPE.WHITE_CLAY.ordinal(),
			28, 5, 26, Block.TYPE.WHITE_CLAY.ordinal(),
			29, 5, 26, Block.TYPE.WHITE_CLAY.ordinal(),
			30, 5, 26, Block.TYPE.WHITE_CLAY.ordinal(),
			
			26, 5, 25, Block.TYPE.WHITE_CLAY.ordinal(),
			27, 5, 25, Block.TYPE.WHITE_CLAY.ordinal(),
			28, 5, 25, Block.TYPE.WHITE_CLAY.ordinal(),
			29, 5, 25, Block.TYPE.WHITE_CLAY.ordinal(),
			30, 5, 25, Block.TYPE.WHITE_CLAY.ordinal(),
			
			26, 5, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			27, 5, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			28, 5, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			29, 5, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			30, 5, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			
			26, 5, 23, Block.TYPE.WHITE_CLAY.ordinal(),
			27, 5, 23, Block.TYPE.WHITE_CLAY.ordinal(),
			28, 5, 23, Block.TYPE.WHITE_CLAY.ordinal(),
			29, 5, 23, Block.TYPE.WHITE_CLAY.ordinal(),
			30, 5, 23, Block.TYPE.WHITE_CLAY.ordinal(),
			
			26, 5, 22, Block.TYPE.WHITE_CLAY.ordinal(),
			27, 5, 22, Block.TYPE.WHITE_CLAY.ordinal(),
			28, 5, 22, Block.TYPE.WHITE_CLAY.ordinal(),
			29, 5, 22, Block.TYPE.WHITE_CLAY.ordinal(),
			30, 5, 22, Block.TYPE.WHITE_CLAY.ordinal(),
			
			26, 5, 21, Block.TYPE.WHITE_CLAY.ordinal(),
			27, 5, 21, Block.TYPE.WHITE_CLAY.ordinal(),
			28, 5, 21, Block.TYPE.WHITE_CLAY.ordinal(),
			29, 5, 21, Block.TYPE.WHITE_CLAY.ordinal(),
			30, 5, 21, Block.TYPE.WHITE_CLAY.ordinal(),
			
			26, 5, 20, Block.TYPE.WHITE_CLAY.ordinal(),
			27, 5, 20, Block.TYPE.WHITE_CLAY.ordinal(),
			28, 5, 20, Block.TYPE.WHITE_CLAY.ordinal(),
//			29, 5, 20, Block.TYPE.WHITE_CLAY.ordinal(),
			30, 5, 20, Block.TYPE.WHITE_CLAY.ordinal(),
			
			26, 5, 19, Block.TYPE.WHITE_CLAY.ordinal(),
			27, 5, 19, Block.TYPE.WHITE_CLAY.ordinal(),
			28, 5, 19, Block.TYPE.WHITE_CLAY.ordinal(),
//			29, 5, 19, Block.TYPE.WHITE_CLAY.ordinal(),
			30, 5, 19, Block.TYPE.WHITE_CLAY.ordinal(),
			
			26, 5, 18, Block.TYPE.WHITE_CLAY.ordinal(),
			27, 5, 18, Block.TYPE.WHITE_CLAY.ordinal(),
			28, 5, 18, Block.TYPE.WHITE_CLAY.ordinal(),
			29, 5, 18, Block.TYPE.WHITE_CLAY.ordinal(),
			30, 5, 18, Block.TYPE.WHITE_CLAY.ordinal(),
			
			// wood pillar
			29, 1, 20, Block.TYPE.OAK_PLANK.ordinal(),
			29, 1, 19, Block.TYPE.OAK_PLANK.ordinal(),
			29, 2, 20, Block.TYPE.OAK_PLANK.ordinal(),
			29, 2, 19, Block.TYPE.OAK_PLANK.ordinal(),
			29, 3, 20, Block.TYPE.OAK_PLANK.ordinal(),
			29, 3, 19, Block.TYPE.OAK_PLANK.ordinal(),
			29, 4, 20, Block.TYPE.OAK_PLANK.ordinal(),
			29, 4, 19, Block.TYPE.OAK_PLANK.ordinal(),
			29, 5, 20, Block.TYPE.OAK_PLANK.ordinal(),
			29, 5, 19, Block.TYPE.OAK_PLANK.ordinal(),
			29, 6, 20, Block.TYPE.OAK_PLANK.ordinal(),
			29, 6, 19, Block.TYPE.OAK_PLANK.ordinal(),
			29, 7, 20, Block.TYPE.OAK_PLANK.ordinal(),
			29, 7, 19, Block.TYPE.OAK_PLANK.ordinal(),
			
			// entrance
			23, 1, 25, Block.TYPE.WHITE_CLAY.ordinal(),
			22, 1, 25, Block.TYPE.WHITE_CLAY.ordinal(),
			21, 1, 25, Block.TYPE.WHITE_CLAY.ordinal(),
			20, 1, 25, Block.TYPE.WHITE_CLAY.ordinal(),
			19, 1, 25, Block.TYPE.WHITE_CLAY.ordinal(),
			18, 1, 25, Block.TYPE.WHITE_CLAY.ordinal(),
			
			23, 1, 26, Block.TYPE.WHITE_CLAY.ordinal(),
			22, 1, 26, Block.TYPE.WHITE_CLAY.ordinal(),
			21, 1, 26, Block.TYPE.WHITE_CLAY.ordinal(),
			20, 1, 26, Block.TYPE.WHITE_CLAY.ordinal(),
			19, 1, 26, Block.TYPE.WHITE_CLAY.ordinal(),
			
			18, 1, 27, Block.TYPE.WHITE_CLAY.ordinal(),
			19, 1, 27, Block.TYPE.WHITE_CLAY.ordinal(),
			23, 1, 27, Block.TYPE.WHITE_CLAY.ordinal(),
			22, 1, 27, Block.TYPE.WHITE_CLAY.ordinal(),
			21, 1, 27, Block.TYPE.WHITE_CLAY.ordinal(),
			20, 1, 27, Block.TYPE.WHITE_CLAY.ordinal(),
			
			18, 1, 28, Block.TYPE.WHITE_CLAY.ordinal(),
			19, 1, 28, Block.TYPE.WHITE_CLAY.ordinal(),
			23, 1, 28, Block.TYPE.WHITE_CLAY.ordinal(),
			22, 1, 28, Block.TYPE.WHITE_CLAY.ordinal(),
			21, 1, 28, Block.TYPE.WHITE_CLAY.ordinal(),
			20, 1, 28, Block.TYPE.WHITE_CLAY.ordinal(),
			
			// front door
			22, 1, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			21, 1, 24, Block.TYPE.GRAY_CLAY.ordinal(),
	
			
			23, 1, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			20, 1, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			23, 2, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			20, 2, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			23, 3, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			20, 3, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			23, 4, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			20, 4, 24, Block.TYPE.WHITE_CLAY.ordinal(),		
			23, 5, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			20, 5, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			23, 6, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			20, 6, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			23, 7, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			20, 7, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			23, 8, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			20, 8, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			23, 9, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			20, 9, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			
			21, 9, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			22, 9, 24, Block.TYPE.WHITE_CLAY.ordinal(),
			
			21, 5, 24, Block.TYPE.WHITE_GLASS.ordinal(),
			22, 5, 24, Block.TYPE.BLACK_GLASS.ordinal(),
			21, 6, 24, Block.TYPE.BLACK_GLASS.ordinal(),
			22, 6, 24, Block.TYPE.WHITE_GLASS.ordinal(),
			21, 7, 24, Block.TYPE.WHITE_GLASS.ordinal(),
			22, 7, 24, Block.TYPE.BLACK_GLASS.ordinal(),
			21, 8, 24, Block.TYPE.BLACK_GLASS.ordinal(),
			22, 8, 24, Block.TYPE.WHITE_GLASS.ordinal(),
			
			
			18, 2, 25, Block.TYPE.BETTER_STONE.ordinal(),
			19, 2, 25, Block.TYPE.BETTER_STONE.ordinal(),
			
			18, 3, 25, Block.TYPE.BETTER_STONE.ordinal(),
			19, 3, 25, Block.TYPE.BETTER_STONE.ordinal(),
			
			18, 4, 25, Block.TYPE.BETTER_STONE.ordinal(),
			19, 4, 25, Block.TYPE.BETTER_STONE.ordinal(),
			
			18, 5, 25, Block.TYPE.BETTER_STONE.ordinal(),
			19, 5, 25, Block.TYPE.BETTER_STONE.ordinal(),
			
			18, 6, 25, Block.TYPE.BETTER_STONE.ordinal(),
			19, 6, 25, Block.TYPE.BETTER_STONE.ordinal(),
			
			18, 7, 25, Block.TYPE.BETTER_STONE.ordinal(),
			19, 7, 25, Block.TYPE.BETTER_STONE.ordinal(),
			
			18, 8, 25, Block.TYPE.BETTER_STONE.ordinal(),
			19, 8, 25, Block.TYPE.BETTER_STONE.ordinal(),
			
			18, 9, 25, Block.TYPE.BETTER_STONE.ordinal(),
			19, 9, 25, Block.TYPE.BETTER_STONE.ordinal(),
			
			// stair
			19, 2, 15, Block.TYPE.COBBLE_BRICK.ordinal(),
			20, 2, 15, Block.TYPE.COBBLE_BRICK.ordinal(),
			19, 3, 14, Block.TYPE.COBBLE_BRICK.ordinal(),
			20, 3, 14, Block.TYPE.COBBLE_BRICK.ordinal(),
			19, 4, 13, Block.TYPE.COBBLE_BRICK.ordinal(),
			20, 4, 13, Block.TYPE.COBBLE_BRICK.ordinal(),
			19, 5, 12, Block.TYPE.COBBLE_BRICK.ordinal(),
			20, 5, 12, Block.TYPE.COBBLE_BRICK.ordinal(),
			19, 5, 11, Block.TYPE.COBBLE_BRICK.ordinal(),
			20, 5, 11, Block.TYPE.COBBLE_BRICK.ordinal(),
			
			18, 6, 11, Block.TYPE.COBBLE_BRICK.ordinal(),
			18, 6, 12, Block.TYPE.COBBLE_BRICK.ordinal(),
			
			17, 7, 11, Block.TYPE.COBBLE_BRICK.ordinal(),
			17, 7, 12, Block.TYPE.COBBLE_BRICK.ordinal(),
			16, 7, 11, Block.TYPE.COBBLE_BRICK.ordinal(),
			16, 7, 12, Block.TYPE.COBBLE_BRICK.ordinal(),
			
			17, 7, 13, Block.TYPE.COBBLE_BRICK.ordinal(),
			16, 7, 13, Block.TYPE.COBBLE_BRICK.ordinal(),
			17, 7, 14, Block.TYPE.COBBLE_BRICK.ordinal(),
			16, 7, 14, Block.TYPE.COBBLE_BRICK.ordinal(),
			
			// front of window
			17, 1, 27, Block.TYPE.COBBLE_BRICK.ordinal(),
			17, 1, 28, Block.TYPE.COBBLE_BRICK.ordinal(),
			17, 1, 29, Block.TYPE.COBBLE_BRICK.ordinal(),
			
			16, 1, 29, Block.TYPE.COBBLE_BRICK.ordinal(),
			15, 1, 29, Block.TYPE.COBBLE_BRICK.ordinal(),
			14, 1, 29, Block.TYPE.COBBLE_BRICK.ordinal(),
			
			13, 1, 27, Block.TYPE.COBBLE_BRICK.ordinal(),
			13, 1, 28, Block.TYPE.COBBLE_BRICK.ordinal(),
			13, 1, 29, Block.TYPE.COBBLE_BRICK.ordinal(),
			
			12, 1, 29, Block.TYPE.COBBLE_BRICK.ordinal(),
			11, 1, 29, Block.TYPE.COBBLE_BRICK.ordinal(),
			10, 1, 29, Block.TYPE.COBBLE_BRICK.ordinal(),
			
			9, 1, 27, Block.TYPE.COBBLE_BRICK.ordinal(),
			9, 1, 28, Block.TYPE.COBBLE_BRICK.ordinal(),
			9, 1, 29, Block.TYPE.COBBLE_BRICK.ordinal(),
			
			// front of window dirt
			14, 1, 27, Block.TYPE.PODZOL.ordinal(),
			15, 1, 27, Block.TYPE.PODZOL.ordinal(),
			16, 1, 27, Block.TYPE.PODZOL.ordinal(),
			
			14, 1, 28, Block.TYPE.PODZOL.ordinal(),
			15, 1, 28, Block.TYPE.PODZOL.ordinal(),
			16, 1, 28, Block.TYPE.PODZOL.ordinal(),
			
			10, 1, 27, Block.TYPE.PODZOL.ordinal(),
			11, 1, 27, Block.TYPE.PODZOL.ordinal(),
			12, 1, 27, Block.TYPE.PODZOL.ordinal(),
			
			10, 1, 28, Block.TYPE.PODZOL.ordinal(),
			11, 1, 28, Block.TYPE.PODZOL.ordinal(),
			12, 1, 28, Block.TYPE.PODZOL.ordinal(),
			
			// wall
			
			18, 1, 26, Block.TYPE.OAK_PLANK.ordinal(),
			18, 2, 26, Block.TYPE.OAK_PLANK.ordinal(),
			18, 3, 26, Block.TYPE.OAK_PLANK.ordinal(),
			18, 4, 26, Block.TYPE.OAK_PLANK.ordinal(),
			18, 5, 26, Block.TYPE.OAK_PLANK.ordinal(),
			18, 6, 26, Block.TYPE.OAK_PLANK.ordinal(),
			18, 7, 26, Block.TYPE.OAK_PLANK.ordinal(),
			
			17, 1, 26, Block.TYPE.OAK_PLANK.ordinal(),
			17, 2, 26, Block.TYPE.OAK_PLANK.ordinal(),
			17, 3, 26, Block.TYPE.OAK_PLANK.ordinal(),
			17, 4, 26, Block.TYPE.OAK_PLANK.ordinal(),
			17, 5, 26, Block.TYPE.OAK_PLANK.ordinal(),
			17, 6, 26, Block.TYPE.OAK_PLANK.ordinal(),
			17, 7, 26, Block.TYPE.OAK_PLANK.ordinal(),
			
			16, 1, 26, Block.TYPE.OAK_PLANK.ordinal(),
			16, 2, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			16, 3, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			16, 4, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			16, 5, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			16, 6, 26, Block.TYPE.OAK_PLANK.ordinal(),
			16, 7, 26, Block.TYPE.OAK_PLANK.ordinal(),
			
			15, 1, 26, Block.TYPE.OAK_PLANK.ordinal(),
			15, 2, 25, Block.TYPE.WHITE_GLASS.ordinal(),
			15, 3, 25, Block.TYPE.WHITE_GLASS.ordinal(),
			15, 4, 25, Block.TYPE.WHITE_GLASS.ordinal(),
			15, 5, 25, Block.TYPE.WHITE_GLASS.ordinal(),
			15, 6, 26, Block.TYPE.OAK_PLANK.ordinal(),
			15, 7, 26, Block.TYPE.OAK_PLANK.ordinal(),
			
			14, 1, 26, Block.TYPE.OAK_PLANK.ordinal(),
			14, 2, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			14, 3, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			14, 4, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			14, 5, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			14, 6, 26, Block.TYPE.OAK_PLANK.ordinal(),
			14, 7, 26, Block.TYPE.OAK_PLANK.ordinal(),
			
			13, 1, 26, Block.TYPE.OAK_PLANK.ordinal(),
			13, 2, 26, Block.TYPE.OAK_PLANK.ordinal(),
			13, 3, 26, Block.TYPE.OAK_PLANK.ordinal(),
			13, 4, 26, Block.TYPE.OAK_PLANK.ordinal(),
			13, 5, 26, Block.TYPE.OAK_PLANK.ordinal(),
			13, 6, 26, Block.TYPE.OAK_PLANK.ordinal(),
			13, 7, 26, Block.TYPE.OAK_PLANK.ordinal(),
			
			12, 1, 26, Block.TYPE.OAK_PLANK.ordinal(),
			12, 2, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			12, 3, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			12, 4, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			12, 5, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			12, 6, 26, Block.TYPE.OAK_PLANK.ordinal(),
			12, 7, 26, Block.TYPE.OAK_PLANK.ordinal(),
			
			11, 1, 26, Block.TYPE.OAK_PLANK.ordinal(),
			11, 2, 25, Block.TYPE.WHITE_GLASS.ordinal(),
			11, 3, 25, Block.TYPE.WHITE_GLASS.ordinal(),
			11, 4, 25, Block.TYPE.WHITE_GLASS.ordinal(),
			11, 5, 25, Block.TYPE.WHITE_GLASS.ordinal(),
			11, 6, 26, Block.TYPE.OAK_PLANK.ordinal(),
			11, 7, 26, Block.TYPE.OAK_PLANK.ordinal(),
			
			10, 1, 26, Block.TYPE.OAK_PLANK.ordinal(),
			10, 2, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			10, 3, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			10, 4, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			10, 5, 25, Block.TYPE.BLACK_GLASS.ordinal(),
			10, 6, 26, Block.TYPE.OAK_PLANK.ordinal(),
			10, 7, 26, Block.TYPE.OAK_PLANK.ordinal(),
			
			9, 1, 26, Block.TYPE.OAK_PLANK.ordinal(),
			9, 2, 26, Block.TYPE.OAK_PLANK.ordinal(),
			9, 3, 26, Block.TYPE.OAK_PLANK.ordinal(),
			9, 4, 26, Block.TYPE.OAK_PLANK.ordinal(),
			9, 5, 26, Block.TYPE.OAK_PLANK.ordinal(),
			9, 6, 26, Block.TYPE.OAK_PLANK.ordinal(),
			9, 7, 26, Block.TYPE.OAK_PLANK.ordinal(),
			
			8, 1, 26, Block.TYPE.OAK_PLANK.ordinal(),
			8, 2, 26, Block.TYPE.OAK_PLANK.ordinal(),
			8, 3, 26, Block.TYPE.OAK_PLANK.ordinal(),
			8, 4, 26, Block.TYPE.OAK_PLANK.ordinal(),
			8, 5, 26, Block.TYPE.OAK_PLANK.ordinal(),
			8, 6, 26, Block.TYPE.OAK_PLANK.ordinal(),
			8, 7, 26, Block.TYPE.OAK_PLANK.ordinal(),
			
			7, 1, 25, Block.TYPE.BETTER_STONE.ordinal(),
			7, 2, 25, Block.TYPE.BETTER_STONE.ordinal(),
			7, 3, 25, Block.TYPE.BETTER_STONE.ordinal(),
			7, 4, 25, Block.TYPE.BETTER_STONE.ordinal(),
			7, 5, 25, Block.TYPE.BETTER_STONE.ordinal(),
			7, 6, 25, Block.TYPE.BETTER_STONE.ordinal(),
			7, 7, 25, Block.TYPE.BETTER_STONE.ordinal(),
			7, 7, 24, Block.TYPE.BETTER_STONE.ordinal(),
			7, 7, 23, Block.TYPE.BETTER_STONE.ordinal(),

			18, 1, 25, Block.TYPE.BETTER_STONE.ordinal(),
			18, 2, 25, Block.TYPE.BETTER_STONE.ordinal(),
			18, 3, 25, Block.TYPE.BETTER_STONE.ordinal(),
			18, 4, 25, Block.TYPE.BETTER_STONE.ordinal(),
			18, 5, 25, Block.TYPE.BETTER_STONE.ordinal(),
			18, 6, 25, Block.TYPE.BETTER_STONE.ordinal(),
			18, 7, 25, Block.TYPE.OAK_PLANK.ordinal(),
			
			17, 1, 25, Block.TYPE.BETTER_STONE.ordinal(),
			17, 2, 25, Block.TYPE.BETTER_STONE.ordinal(),
			17, 3, 25, Block.TYPE.BETTER_STONE.ordinal(),
			17, 4, 25, Block.TYPE.BETTER_STONE.ordinal(),
			17, 5, 25, Block.TYPE.BETTER_STONE.ordinal(),
			17, 6, 25, Block.TYPE.BETTER_STONE.ordinal(),
			17, 7, 25, Block.TYPE.OAK_PLANK.ordinal(),
			
			16, 1, 25, Block.TYPE.BETTER_STONE.ordinal(),
			16, 6, 25, Block.TYPE.BETTER_STONE.ordinal(),
			16, 7, 25, Block.TYPE.OAK_PLANK.ordinal(),
			
			15, 1, 25, Block.TYPE.BETTER_STONE.ordinal(),
			15, 6, 25, Block.TYPE.BETTER_STONE.ordinal(),
			15, 7, 25, Block.TYPE.OAK_PLANK.ordinal(),
			
			14, 1, 25, Block.TYPE.BETTER_STONE.ordinal(),
			14, 6, 25, Block.TYPE.BETTER_STONE.ordinal(),
			14, 7, 25, Block.TYPE.OAK_PLANK.ordinal(),
			
			13, 1, 25, Block.TYPE.BETTER_STONE.ordinal(),
			13, 2, 25, Block.TYPE.BETTER_STONE.ordinal(),
			13, 3, 25, Block.TYPE.BETTER_STONE.ordinal(),
			13, 4, 25, Block.TYPE.BETTER_STONE.ordinal(),
			13, 5, 25, Block.TYPE.BETTER_STONE.ordinal(),
			13, 6, 25, Block.TYPE.BETTER_STONE.ordinal(),
			13, 7, 25, Block.TYPE.OAK_PLANK.ordinal(),
			
			12, 1, 25, Block.TYPE.BETTER_STONE.ordinal(),
			12, 6, 25, Block.TYPE.BETTER_STONE.ordinal(),
			12, 7, 25, Block.TYPE.OAK_PLANK.ordinal(),
			
			11, 1, 25, Block.TYPE.BETTER_STONE.ordinal(),
			11, 6, 25, Block.TYPE.BETTER_STONE.ordinal(),
			11, 7, 25, Block.TYPE.OAK_PLANK.ordinal(),
			
			10, 1, 25, Block.TYPE.BETTER_STONE.ordinal(),
			10, 6, 25, Block.TYPE.BETTER_STONE.ordinal(),
			10, 7, 25, Block.TYPE.OAK_PLANK.ordinal(),
			
			8, 7, 24, Block.TYPE.OAK_PLANK.ordinal(),
			9, 7, 24, Block.TYPE.OAK_PLANK.ordinal(),
			10, 7, 24, Block.TYPE.OAK_PLANK.ordinal(),
			11, 7, 24, Block.TYPE.OAK_PLANK.ordinal(),
			12, 7, 24, Block.TYPE.OAK_PLANK.ordinal(),
			13, 7, 24, Block.TYPE.OAK_PLANK.ordinal(),
			14, 7, 24, Block.TYPE.OAK_PLANK.ordinal(),
			15, 7, 24, Block.TYPE.OAK_PLANK.ordinal(),
			16, 7, 24, Block.TYPE.OAK_PLANK.ordinal(),
			17, 7, 24, Block.TYPE.OAK_PLANK.ordinal(),
			18, 7, 24, Block.TYPE.OAK_PLANK.ordinal(),
			
			8, 7, 23, Block.TYPE.OAK_PLANK.ordinal(),
			9, 7, 23, Block.TYPE.OAK_PLANK.ordinal(),
			10, 7, 23, Block.TYPE.OAK_PLANK.ordinal(),
			11, 7, 23, Block.TYPE.OAK_PLANK.ordinal(),
			12, 7, 23, Block.TYPE.OAK_PLANK.ordinal(),
			13, 7, 23, Block.TYPE.OAK_PLANK.ordinal(),
			14, 7, 23, Block.TYPE.OAK_PLANK.ordinal(),
			15, 7, 23, Block.TYPE.OAK_PLANK.ordinal(),
			16, 7, 23, Block.TYPE.OAK_PLANK.ordinal(),
			17, 7, 23, Block.TYPE.OAK_PLANK.ordinal(),
			18, 7, 23, Block.TYPE.OAK_PLANK.ordinal(),
			
			9, 1, 25, Block.TYPE.OAK_PLANK.ordinal(),
			9, 2, 25, Block.TYPE.OAK_PLANK.ordinal(),
			9, 3, 25, Block.TYPE.OAK_PLANK.ordinal(),
			9, 4, 25, Block.TYPE.OAK_PLANK.ordinal(),
			9, 5, 25, Block.TYPE.OAK_PLANK.ordinal(),
			9, 6, 25, Block.TYPE.OAK_PLANK.ordinal(),
			9, 7, 25, Block.TYPE.OAK_PLANK.ordinal(),
			
			8, 1, 25, Block.TYPE.OAK_PLANK.ordinal(),
			8, 2, 25, Block.TYPE.OAK_PLANK.ordinal(),
			8, 3, 25, Block.TYPE.OAK_PLANK.ordinal(),
			8, 4, 25, Block.TYPE.OAK_PLANK.ordinal(),
			8, 5, 25, Block.TYPE.OAK_PLANK.ordinal(),
			8, 6, 25, Block.TYPE.OAK_PLANK.ordinal(),
			8, 7, 25, Block.TYPE.OAK_PLANK.ordinal(),
			
			// side wall
			6, 1, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 28, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 27, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 26, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 25, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 24, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 23, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 22, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 21, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 20, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 19, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 18, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 17, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 16, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 15, Block.TYPE.GRAY_CLAY.ordinal(),
			
			6, 1, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 2, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 3, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 4, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 5, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 6, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			6, 7, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 1, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 2, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 3, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 4, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 5, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 6, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			5, 7, 14, Block.TYPE.GRAY_CLAY.ordinal(),
			
			// floor
			19, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			
			23, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 24, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 23, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 14, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 13, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 12, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 11, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 10, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 9, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 8, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			23, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			22, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			21, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			20, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			19, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			7, 1, 7, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			// 2nd floor
			7, 7, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 7, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 7, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 7, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 7, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 7, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 7, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 7, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 7, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 7, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 7, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 7, 22, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			7, 7, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 7, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 7, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 7, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 7, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 7, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 7, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 7, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 7, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 7, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 7, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 7, 21, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			7, 7, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 7, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 7, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 7, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 7, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 7, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 7, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 7, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 7, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 7, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 7, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 7, 20, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			7, 7, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 7, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 7, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 7, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 7, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 7, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 7, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 7, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 7, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 7, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 7, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 7, 19, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			7, 7, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 7, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 7, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 7, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 7, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 7, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 7, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 7, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 7, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 7, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 7, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 7, 18, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			7, 7, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 7, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 7, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 7, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 7, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 7, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 7, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 7, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 7, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 7, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 7, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 7, 17, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			7, 7, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 7, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 7, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 7, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 7, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 7, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 7, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 7, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 7, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 7, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 7, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 7, 16, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			7, 7, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			8, 7, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			9, 7, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			10, 7, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			11, 7, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			12, 7, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			13, 7, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			14, 7, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			15, 7, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			16, 7, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			17, 7, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			18, 7, 15, Block.TYPE.JUNGLE_PLANK.ordinal(),
			
			// 2n floor front
			18, 9, 22, Block.TYPE.BETTER_STONE.ordinal(),
			18, 10, 22, Block.TYPE.BETTER_STONE.ordinal(),
			17, 9, 22, Block.TYPE.BETTER_STONE.ordinal(),
			17, 10, 22, Block.TYPE.BETTER_STONE.ordinal(),
			
			5, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			6, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			7, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			8, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			9, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			10, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			11, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			12, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			13, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			14, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			15, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			16, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			17, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			18, 8, 22, Block.TYPE.BETTER_STONE.ordinal(),
			
			5, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			6, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			7, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			8, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			9, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			10, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			11, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			12, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			13, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			14, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			15, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			16, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			17, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			18, 11, 22, Block.TYPE.BETTER_STONE.ordinal(),
			
		};
	
}
